### ISSUE TITLE
Remove Nicehash External options

### ISSUE THREAD

**Issue by grantemsley** [UselessGuru/UG-Miner#2]
Remember me? Glad to see you're still working on this, and that some of my code lives on!

Nicehash no longer supports external accounts, so should probably start removing that. Even with accounts and using internal addresses, people may want to reconsider using NiceHash after many reports of people having issues verifying their identity and submitting drivers licenses and such for identification, which is now required for any withdrawls.

> Starting November 12, 2024, mining directly to an external Bitcoin wallet will no longer be possible.

> To continue mining on NiceHash, all you have to do is [create an account](https://www.nicehash.com/my/register) and follow the connection instructions [here](https://www.nicehash.com/support/mining-help/asic-mining/how-to-connect-your-asic-machine-to-nicehash).

**Comment by UselessGuru** [comment]
> Remember me?

Yes. Sure. 

> Nicehash no longer supports external accounts

Thank you. I will make the necessary changes.

**Comment by UselessGuru** [comment]
Fixed in 6.3.13
