### ISSUE TITLE
Remove MiningPoolHub?

### ISSUE THREAD

**Issue by grantemsley** [UselessGuru/UG-Miner#3]
Per your own issue on [RainbowMiner back in March](https://github.com/RainbowMiner/RainbowMiner/issues/2725), MiningPoolHub seems to be unusable and not responding to anyone.

Has that changed and they're ok again? Or should it be removed from UG-Miner as well?

**Comment by UselessGuru** [comment]
> Has that changed and they're ok again? Or should it be removed from UG-Miner as well?

I thought I had removed the files in 6.3.0... ???

> Changelog UG-Miner 6.3.0 2024/09/01
> - Removed pool 'MiningPoolHub'. Pool is no longer trustworthy. Outstanding balances will not get paid and support will not respond.

On each update MPM will get removed from the config anyway :-)
I will remove the relevant files again in the next version (there are no changes required in the code).

**Comment by UselessGuru** [comment]
Fixed in 6.3.13
